name: 'finscope'
version: '1.0.0'
config-version: 2

profile: 'finscope'

model-paths: ["models"]
test-paths: ["tests"]

models:
  finscope:
    staging:
      +materialized: table
    marts:
      +materialized: table
